# Generated by Django 4.1.6 on 2023-03-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pic',
            name='pic',
            field=models.TextField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='pic',
            name='picurl',
            field=models.TextField(default='-', max_length=100),
        ),
    ]
